### ISSUE TITLE
Update to MC 1.20.1

### ISSUE THREAD

**Issue by Aabaddon** [StoneLabs/delayed-respawn#4]
Could you please update this mod? it is just what i am looking for and there is no other mod that does it in the lastest versions... is for a lan server with friends

**Comment by StoneLabs** [comment]
Yea sure I can update it to 1.20.1, shouldn't be difficult. I'll do it when I find the time.
It might take a week or two before I get to it, sorry :(

If anyone wants to do it before me, feel free to make a PR. I'd appreciate it :)

**Comment by StoneLabs** [comment]
Done with Version 1.5 (ced6a15)

[> Modrinth](https://modrinth.com/mod/delayed-respawn/version/1.5.0)

[> GH Release](https://github.com/StoneLabs/delayed-respawn/releases/tag/v1.5.0)
